services:
  product:
    build: microservices/product-service
    mem_limit: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  recommendation:
    build: microservices/recommendation-service
    mem_limit: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    build: microservices/review-service
    mem_limit: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 512M
    ports:
      - 7000:7000
    environment:
      - SPRING_PROFILES_ACTIVE=docker